apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-db-ext-secret
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: azure-kv-store
  target:
    name: authentik-db-secret 
    creationPolicy: Owner
  data:
  - secretKey: password  
    remoteRef:
      key: pg-password      

