apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: azure-kv-store
  namespace: authentik
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: "https://AksCloudKeyVaultDJO.vault.azure.net"

